name: Equestrian America
favicon: null
layout_spectrum: 0.36527
typography_spectrum: 0.8637993
title: 'Equestrian America: A Celebration of Equine Culture and Competition'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#335078'
    - '#000001'
    - '#fefefe'
    - '#acb9ca'
    - '#8e0017'
  brandStrength: 0.9014337
  lightness: 0.5949821
  saturation: 0.2544803
  rhythmicContrast: 0.7029717
purpose: []
