name: Equestrian America
favicon: null
layout_spectrum: 0.70541
typography_spectrum: 0.15324
title: 'Equestrian America: A Celebration of Equestrian Culture and Competition'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a4ddf3'
    - '#000000'
    - '#00c6cb'
    - '#d70000'
    - '#5a5b61'
  brandStrength: 0.7856048652902246
  lightness: 0.5
  saturation: 0.1875
  rhythmicContrast: 0.7029717215336859
purpose: []
