name: Equestrian America
favicon: null
layout_spectrum: 0
typography_spectrum: 0.8637993
title: 'Equestrian America: A Celebration of Equestrian Culture and Competition'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d4eaff'
    - '#5c92ea'
    - '#030e22'
    - '#aea376'
    - '#0f460d'
  brandStrength: 0.9014337
  lightness: 0.5949821
  saturation: 0.2544803
  rhythmicContrast: 0.7029717
purpose: []
