name: Equestrian America
favicon: null
layout_spectrum: 0.55445
typography_spectrum: 0.15324
title: A Celebration of Equestrian Competition and Culture
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dfe6f0'
    - '#111119'
    - '#a2a23e'
    - '#47464b'
    - '#769bc9'
  brandStrength: 0.7856048652902246
  lightness: 0.6148162591271102
  saturation: 0.125
  rhythmicContrast: 0.7029717215336859
purpose: []
